version: '3.3'

services:
  jakach-login-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: jakach-login-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      jakach-login-network:
        ipv4_address: 192.168.5.2
    volumes:
      - jakach-login-db-storage:/var/lib/mysql

  jakach-login-srv:
    build:
      context: .
      dockerfile: srv_dockerfile
    container_name: jakach-login-srv
    networks:
      jakach-login-network:
        ipv4_address: 192.168.5.3
    ports:
      - "444:443"
    depends_on:
      - jakach-login-db
    volumes:
      - ./app-code:/var/www/html
      - ./apache-conf:/etc/apache2/sites-available
      - ./php-conf:/usr/local/etc/php/
      - ./certs:/etc/apache2/certs
networks:
  jakach-login-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24

volumes:
  jakach-login-db-storage:
    external: true
